version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  webapp:
    build:
      context: ./src      
      dockerfile: OperatorCode.Api/Dockerfile
    ports:
      - 5000:8080
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
    driver: local